### PR TITLE
WIP: document build steps in travis

### PR DESCRIPTION
**Pull request by qyanu**
Pre-Script: This pull request is based on https://github.com/potassco/guide/pull/28 and thus WIP until that one has been adjudicated.

In addition to https://github.com/potassco/guide/pull/28 i would propose to document the build steps necessary to generate the release files 'guide.pdf' and 'examples.zip' in travis.yml.
- Advantage in the short time is higher reproducibility of build by third parties.
- In the long term, building release files and uploading them to a github tag via travis might be considered.

As a disadvantage of note is, that the cpu-workload onto travis is increased by the commits in this pull-request, and thus available credits at travis-ci has to be considered before merging.

with kind regards,
Max

### CODE REVIEW

**Comment by rkaminsk** [comment]
The guide should better be build with a tool automatically running bibtex and co. One such tool is [latexmk](https://mg.readthedocs.io/latexmk.html):
```bash
latexmk -pdf guide.tex
```
In a lot of projects we also switched to github actions, which are a bit more modern than travis and in my opinion easier to use. Something like this can be used:
```yaml
name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Compile
      run: docker run -v $(pwd):/mnt -w '/mnt' -e TEXINPUTS='.//:' listx/texlive:2018 latexmk -pdf --latexoption=--interaction=nonstopmode guide.tex
    - name: Upload
      uses: actions/upload-artifact@master
      with:
        name: pdf
        path: guide.pdf
```

**Comment by qyanu** [comment]
I see. Let me process your message tomorrow or sunday, but a related question: why use --interaction=nonstopmode in the first place? shouldn't the build fail if there are some bad commands used?

**Comment by rkaminsk** [comment]
> I see. Let me process your message tomorrow or sunday, but a related question: why use --interaction=nonstopmode in the first place? shouldn't the build fail if there are some bad commands used?

pdflatex opens a command line prompt, when there is an error for the user to fix it. The nonstopmode is, in my opinion at least, the only sensible option.

**Comment by rkaminsk** [comment]
Actually, we have standard way to handle our tex documents. This project here is just a bit dated and has not been updated. I'll adjust it later. Still, thanks for looking at it!

**Comment by rkaminsk** [comment]
Check the [Actions](https://github.com/potassco/guide/actions) tab. If you click on a run, you can also download the associated artifacts without having to build the guide yourself.

**Comment by qyanu** [comment]
@rkaminsk it seems i won't be playing around with github-actions on the weekend then :-)
thanks for the update!

**Pull request closed without merging**
